### ISSUE TITLE
Problem in installing the run file.

### ISSUE THREAD

**Issue by jeetu2312** [animikhaich/Timelapse-Creator#1]
Traceback (most recent call last):
  File "main.py", line 3, in <module>
    from video_utils import bulk_validate_video, bulk_video_converter
  File "/home/ani/miniconda3/envs/gui/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "video_utils.py", line 4, in <module>
    import cv2
  File "/home/ani/miniconda3/envs/gui/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 623, in exec_module
  File "site-packages/cv2/__init__.py", line 5, in <module>
ImportError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/_MEIVWNRO7/./libglib-2.0.so.0)
[11479] Failed to execute script main

**Comment by animikhaich** [comment]
This issue came because the file was composed in `Ubuntu 19.10`, which contains `libc6 of version 2.30`. However, older `Ubuntu 18.04` has a max `libc6 version of 2.27`. This created the compatibility issue. 

Immediate Solution: You can download and install libc6 2.30:
- `wget http://mirrors.kernel.org/ubuntu/pool/main/g/glibc/libc6_2.30-0ubuntu2_amd64.deb`
- `sudo dpkg -i libc6_2.30-0ubuntu2_amd64.deb`

Long term solution: I will fix this bug by compiling at different OS versions in the next release. 

Thanks for reporting the bug.
